# Generated by Django 2.2.1 on 2019-07-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='format_audio',
            field=models.FileField(blank=True, null=True, upload_to='Sermon/Audio/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='format_doc',
            field=models.FileField(blank=True, null=True, upload_to='Sermon/Document/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='format_video',
            field=models.FileField(blank=True, null=True, upload_to='Sermon/Video/'),
        ),
    ]
