# Generated by Django 2.2.1 on 2019-07-07 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190707_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='news-item'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 22, 57, 24, 15040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 22, 57, 24, 15040, tzinfo=utc)),
        ),
    ]
