# Generated by Django 2.2.1 on 2019-07-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190707_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(default='sermonDetail'),
            preserve_default=False,
        ),
    ]
