# Generated by Django 2.2.1 on 2019-07-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sermon_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='picture',
            field=models.ImageField(null=True, upload_to='Sermon/pictures'),
        ),
    ]
