# Generated by Django 2.2.1 on 2019-07-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_sermon_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
